### PR TITLE
Context menu actions for copying attachments names and tags

### PR DESCRIPTION
**Pull request by Armagedoom**
Feature request: #617

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I don't think we should have a button for each tag, otherwise the UI will become cluttered quickly, there should be instead a context menu action.

**Comment by Armagedoom** [comment]
I agree, and also agree that this is a temporary solution for #20, which will render this unnecessary.
Since the icon is only shown on mouse hover, and it is more accessible and faster to go for the specific tag you want (with less clicks), would you reconsider?
Here are images of the result. If you still don't like it I will try to go for the context menu.
image
image

**Comment by fabiospampinato** [comment]
Sorry but I think a context-menu option would be better as not everyone would need this and adding this as a context-menu option would cause less disruption to the UI.

**Comment by Armagedoom** [comment]
You got it.
Thanks!

**Comment by Armagedoom** [comment]
I found out this is also necessary for attachments.
Otherwise, whenever you attach a file and you want to get its reference, you have to go to the folder and copy the path there instead of being able to stay in Notable for doing so.
If you are ok with this I can include it in this Pull request, just let me know.

**Comment by fabiospampinato** [comment]
@Armagedoom Right, it seems appropriate that the `Copy` action is available on both lists 👍

**Comment by Armagedoom** [comment]
The context menu / copy button for attachments is developed but doesn't work as intended because of this bug: https://github.com/notable/notable/issues/580#issuecomment-485110205
IMO this pull can be merged because this misbehavior happens also with the rest of the items of the context menu.

**Comment by Armagedoom** [comment]
The pull request https://github.com/notable/notable/pull/622 fixes the described misbehavior.

**Comment by fabiospampinato** [comment]
Thanks for the PR, I'll try to get this merged as soon as I can.

I have a couple of suggestions/some feedback:

1. I'm not sure I like that the label for those buttons is different. Perhaps it should just say "Copy" on both, even though actually "copying" at attachment may mean that the actual file may be copied to the clipboard 🤔 
2. Perhaps for completeness these context menu items should also be added elsewhere in the app (in the sidebar for tags, and in rendered attachments in the preview component) 🤔 

What do you think?

**Comment by Armagedoom** [comment]
I like it. Updated with your remarks (all of them)!

**Comment by fabiospampinato** [comment]
Thank you @Armagedoom! I've made a few changes to this here (5f0edf9bc5def0813dfed103a6cce6e20359eba1), if you want to take a look at them, there were few minor problems and things that could be improved.

**Pull request merged**
