### PR TITLE
:sparkles: render HTML within middlebar note title - #563

### LINKED ISSUE #563: Middlebar Note title encoding HTML entities; not showing :emojis:
The middlebar is showing encoded HTML entities and not showing emojis using colon syntax.

**EXAMPLE**

Screen Shot 2019-03-18 at 7 10 36 AM

I'm assuming the first part could be resolved if the title text was set using `dangerouslySetInnerHTML` [here](https://github.com/notable/notable/blob/9817109d22d20a45532d10e08ddbd6216cbef12f/src/renderer/components/main/middlebar/note.tsx#L18).

(This may be two separate issues. Also, I tried to look and didn't see this reported yet; apologies if it's known)

- **OS Version**: macOS 10.14
- **Notable Version**: 1.4.0

### Current behavior

Create a new note with special characters and/or emojis using colons in the title.

### Expected behavior

Middlebar note title shows character instead of entity; shows emoji (preferable) or text for emojis.  For example: `# Handles :sparkles: & 🦄 &copy;` should show a note titled "Handles ✨ & 🦄 ©"

### PR DESCRIPTION
**Pull request by blakek**
Notes created with HTML entities in the title now render the HTML version instead of encoded entities.

Resolves #563

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Thanks for the PR! I'm not sure this is the best solution though, `dangerouslySetInnerHTML` shouldn't be used, and while we are currently using it in one spot we should work towards avoiding using it entirely rather than using it more.

I this maybe decoding those html entities might be a better option. https://www.npmjs.com/package/html-entities

**Comment by blakek** [comment]
👍 Updated. Not sure if I added it to the right place or not, though. I added it there because I was assuming anywhere `getTitle` was called you'd want the decoded version.

**Comment by fabiospampinato** [comment]
Thank you @blakek!

I think maybe we should decode the title as soon as possible, i.e. when notes get read/updated/created, rather then when the title is rendered in order to avoid eccessive calls to the html decoder 🤔

**Comment by blakek** [comment]
@fabiospampinato Would you prefer if the title were decoded in [`_inferTitleFromFilePath`](https://github.com/notable/notable/blob/master/src/renderer/containers/main/note.ts#L50) and [`_inferTitleFromLine`](https://github.com/notable/notable/blob/master/src/renderer/containers/main/note.ts#L56)? It seems they're called on note duplicate/save/sanitize. It looks like on a new note is created, the title uses `"Untitled"`, so it wouldn't be necessary then.

**Comment by fabiospampinato** [comment]
@blakek I'm not sure, I'll have to take a closer look at this.

**Comment by fabiospampinato** [comment]
@blakek it looks like decoding on `_inferTitleFromLine` is the best option, thanks for the PR, I've implemented this [here](https://github.com/notable/notable/commit/a771003029ed4e9f2a7f73a19417c53a5ab6119f).

**Pull request closed without merging**
