### PR TITLE
Add renovate

### PR DESCRIPTION
**Pull request by JamieMagee**
[Renovate](https://renovatebot.com/) is an automated dependency updater. This PR adds a barebones config for renovate. In order to enable renovate, you'll have to [Install the GitHub App](https://renovatebot.com/docs/install-github-app/) (It's free for open source projects).

After your merge this PR, and install the GitHub App, renovate will open a PR to convert your dependencies from ranges to pinned versions (See [this PR](https://github.com/JamieMagee/notable/pull/1) for an example). Pinned versions give you the benefit of having a reproducible build, and ranges aren't required when the pinned versions can be updated automatically. Renovate has a [great page about range vs pin](https://renovatebot.com/docs/dependency-pinning/).

Renovate is extremely flexible in it's configuration, and can allow automerging of minor version bumps, required reviewers for PRs, auto adding tags, etc. Check out the [configuration options](https://renovatebot.com/docs/configuration-options/) page for a complete overview, or let me know what sort of behaviour you expect from renovate, and I can adjust the config here.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
@JamieMagee Thanks for the PR but I don't like those kinds of bots. 

>  Pinned versions give you the benefit of having a reproducible build

Not true actually, as those pinned dependencies will themselves probably have non-pinned dependencies, you need a lockfile for reproducible builds.

> Renovate is extremely flexible in it's configuration, and can allow automerging of minor version bumps, required reviewers for PRs, auto adding tags, etc.

Honestly even just the time required to configure these sorts of programs is probably not worth it for me. Plus not all projects are using semantic versioning, and sometimes I prefer to read the actual commits log.

**Comment by JamieMagee** [comment]
Is it possible to have a discussion about this? I truly believe that renovate can help lighten the burden of keeping dependencies up to date.

> Not true actually, as those pinned dependencies will themselves probably have non-pinned dependencies, you need a lockfile for reproducible builds.

True, but renovate also maintains `package-json.lock`. See [the sample PR](https://github.com/JamieMagee/notable/pull/1/files#diff-32607347f8126e6534ebc7ebaec4853d).

> Honestly even just the time required to configure these sorts of programs is probably not worth it for me. Plus not all projects are using semantic versioning, and sometimes I prefer to read the actual commits log.

I wasn't suggesting you go through and configure it right now. The default config is sensible, and will only have a maximum of 2 PRs open at a time, that you have to manually merge (just like any other PR). Automerging of minor version bumps was just an example of what you could configure, not a suggestion of what to do.

Check out [this PR for `@types/node`](https://github.com/JamieMagee/notable/pull/2) to see the information it gives you. It includes a link to the GitHub repository so you can check out the commit log.

**Comment by fabiospampinato** [comment]
> Is it possible to have a discussion about this? 

Sure. 

> I truly believe that renovate can help lighten the burden of keeping dependencies up to date.

It feels a bit like the opposite way to me. I just don't think there's a big burden to be lifted, and I see learning renovate instead as the extra burden here.

> True, but renovate also maintains package-json.lock. See the sample PR.

Ok, I'm not sure why dependencies are being pinned then. Maybe for avoiding updating them when installing a new one? That could be useful I guess, but for solving this issue switching to a better package manager could probably be a better option over all (I think yarn doesn't have this problem but I might be wrong).

> I wasn't suggesting you go through and configure it right now.

If it's not now it'll be later, and that doesn't look like time well spent to me.

> The default config is sensible

Maybe, but I don't know what it is or how this thing works, I only know that the problem it solves is pretty marginal for me.

**Comment by JamieMagee** [comment]
> It feels a bit like the opposite way to me. I just don't think there's a big burden to be lifted, and I see learning renovate instead as the extra burden here.

I've been using renovate personally and professionally for a while now, and I don't think it's difficult to use. Honestly it's been set-and-forget. On the other hand, I no longer have to be so worried about keeping an eye on security alerts for vulnerable dependencies. [GitGub does bring the alerts to you](https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies), but it's even easier when the updates come to you too.

> Ok, I'm not sure why dependencies are being pinned then. Maybe for avoiding updating them when installing a new one? That could be useful I guess, but for solving this issue switching to a better package manager could probably be a better option over all (I think yarn doesn't have this problem but I might be wrong).

I'll summaries [this example from the renovate docs](https://renovatebot.com/docs/dependency-pinning/#why-pin-dependencies). Imagine you specify `"my-dependency": "^1.0.0"`, and `npm` resolves it to `1.1.0`. Now, a new version with a breaking change/bug/whatever, `1.2.0` is published. Your `master` branch is now broken because `npm` resolves `^1.0.0` to `1.2.0`.

`npm` has tried to solve this issue with the [`npm ci`](https://docs.npmjs.com/cli/ci.html), but it's not very well known. `yarn` does appear to have better default behaviour, but [the docs](https://yarnpkg.com/lang/en/docs/cli/install/) say you have to add the `--frozen-lockfile` flag to guarantee no changes to `yarn.lock`

(as an aside renovate also supports `yarn`)

>Maybe, but I don't know what it is or how this thing works, I only know that the problem it solves is pretty marginal for me.

If you are into podcasts, I would recommend [Automated dependency updates from The Changelog](https://changelog.com/podcast/289) podcast. It's where I first learned about renovate, and gives a a lot more info about the concept of automating dependency updates (They also provide a transcript if you want to Ctrl+F).

**Comment by fabiospampinato** [comment]
I'll try to document myself more on the matter, thanks for the suggestion 👍

**Comment by fabiospampinato** [comment]
Btw I'm using [this](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) extension for vscode that shows me what the current version is and a way to update the dependency with one click:

screen shot 2019-03-05 at 17 25 14


Maybe that's lowering the burden of dependencies management for me.

**Comment by JamieMagee** [comment]
True, but it still requires that you have access to vscode, and manually run tests (I know there aren't any for notable yet, but let's assume there are), create a commit, and push to GitHub.

If the commits and PRs are created automatically, regardless of what you're doing, and tests are run automatically for each PR, all you need is access to a web browser to review small changes (like patches).

**Pull request closed without merging**
