### PR TITLE
run KaTeX before showdown

### PR DESCRIPTION
**Pull request by ntessore**
This runs KaTeX on the raw `render` input string before it is passed to showdown. Since KaTeX produces HTML, which I believe showdown leaves completely alone, this should be transparent to all non-math output. It seems to get rid of almost all formatting problems, which are due to showdown escaping/normalisation interference (which cannot be fixed in an extension).

The format is what I perceive to be the most common and useful one where everything between single `$` is converted to inline math, and everything between `$$` is converted to display math, **ignoring newlines**. This means in particular that all KaTeX environments now work as expected.

I have left the ` ```katex` code blocks alone, to not break anyone's notes. Since this seems like it was a workaround, it might be desirable to take it out entirely.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
> which cannot be fixed in an extension

What specific problem can't be fixed in an extension?

**Comment by ntessore** [comment]
@fabiospampinato You need the LaTeX newline symbol `\\` to make matrices and multiline equations etc., which seems to always be sanitised to `\` by showdown. But `\` as input is a symbol too (space), so there seems to be no way to distinguish between the two once showdown has run.

**Comment by fabiospampinato** [comment]
@ntessore I see 🤔Thanks for the contribution, I'll have to deal with a few more things first, then I'll consider merging this.

The modified regex looks too simple though, there's a lot of useful logic in there that we shouldn't just throw out: 

- special character escaping (`\$`)
- number after special characters (`$asd$2`)
- things like `$amp;` and `$nbsp;`, which currently are mostly produced by showdown, but somebody might write that manually too, or for instance the Evernote importer we are using sometimes add some `$nbsp;`s
- formulas starting/ending with spaces `$ this is not a formula $`

**Comment by ntessore** [comment]
I have replaced the regex with the backend of KaTeX's own auto-render function. That is a lot more powerful than the regex, and uses the delimiters from the config. For example, the following works as expected, note the nested text with `$...$` and the escaped dollars:

```tex
$\text{if~$x=1$}$
the apples cost \$12 and the computer costs \$20
```

With configurable delimiters, perhaps the easiest way out would be to not have `$` be for TeX by default (that is also how KaTeX handles it).

**Comment by fabiospampinato** [comment]
Good, another issue is that we are transforming AsciiMath syntax to LaTeX, that I guess would have to also run before KaTeX itself.

**Comment by ntessore** [comment]
I have added support for that using the same mechanism, configured through the delimiters. 

I don't understand everything that is going on in the original regex, so I have not touched that part for AsciiMath.

Filtering out all the special cases you mentioned should be much easier, you can provide a blacklist of non-math expressions against which each chunk is tested.

**Comment by ntessore** [comment]
This still needs some additional protection for code blocks.

**Comment by ntessore** [comment]
With bb214a1 the code blocks with backticks and four spaces should be recognised and ignored. The regex might need a bit of fine-tuning for edge cases etc.

**Comment by ntessore** [comment]
With 176ce55 the code blocks with backticks and four spaces should be recognised and ignored. The regex might need a bit of fine-tuning for edge cases etc.

**Comment by fabiospampinato** [comment]
Let me switch to marked #531 first (so that I'll also have a chance to re-organize our markdown rendering pipeline) and then I'll work on merging this 👍

**Comment by fabiospampinato** [comment]
Implemented in v1.6.

**Pull request closed without merging**
