### PR TITLE
Fixed the images

### PR DESCRIPTION
**Pull request by jeremygautama**
Now you can see the images again :)

turns out you just need to change the link

### CODE REVIEW

**Comment by jeremygautama** [comment]
Fixed the images for the README.md*

**Comment by jeremygautama** [comment]
This is the result
fixed

**Comment by jeremygautama** [comment]
And yes,
other pictures also show up

other fix

**Comment by fabiospampinato** [comment]
Thanks for the PR but this doesn't actually solve it, it just requests the same images more indirectly. The problem is only in Safari. I need to update the server to workaround whatever the people at GitHub did to break this again.

image

**Comment by fabiospampinato** [comment]
Now it's fixed for good.

**Pull request closed without merging**
