### PR TITLE
Add Markdown Calc Extension

### PR DESCRIPTION
**Pull request by kmccullen97**
Markdown Calc allows you to run calculations in a markdown table similar to excel ([Repo](https://github.com/kmccullen97/md-calc)).

To test just add "mdCalc" before a table and it will be evaluated

Example
```
mdCalc
| Test |     |        |
| ---- | --- | ------ |
| 10   | 5   | =A1+B1 |
```
will result in
|Test|||
|-|-|-|
|10|5|15|

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Until this is super mature and powerful something like this should really be implemented as an external plugin, now we don't have plugins _yet_ unfortunately, but I think you can hack something up using the custom JS editor that ships with v1.9 (https://github.com/notable/notable-insiders/releases).

You might want to consider sharing your customization with the people in the [chat](https://chat.notable.app).

**Comment by kmccullen97** [comment]
What channel in that chat would be best for mentioning this customization?

**Comment by fabiospampinato** [comment]
Maybe "Other Customizations"?

**Comment by kmccullen97** [comment]
Is the only way to make edits from the Custom JS Editor through the DOM?

**Comment by fabiospampinato** [comment]
Yes there are no APIs exposed just yet.

**Pull request closed without merging**
