### PR TITLE
Use checkbox menu type for "Toggle" commands

### PR DESCRIPTION
**Pull request by RomanKornev**
Changes:
- `Toggle Focus Mode` as checkbox
- `Toggle Full Screen` as checkbox
- `Toggle Developer Tools` as checkbox
- `Toggle Split-View` as checkbox

That's how it is in VSCode for example.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
> That's how it is in VSCode for example.

Can you show me the code in vscode's repo?

If we can't detect the current state and update the menu accordingly then there's no point in this change.

**Comment by RomanKornev** [comment]
> Can you show me the code in vscode's repo?

I'll try to look for it.

> If we can't detect the current state and update the menu accordingly

Maybe we can, I just don't know how.

> no point in this change

Everything except split-view works and updates correctly though.

**Comment by RomanKornev** [comment]
[toggleRenderWhitespace.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/toggleRenderWhitespace.ts) View - Toggle Render Whitespace

[breadcrumbsControl.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts) View - Toggle Breadcrumbs

[toggleRenderControlCharacter.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/toggleRenderControlCharacter.ts) View - Toggle Control Characters

**Comment by RomanKornev** [comment]
I fixed it. It now checks split-view state as well.

Eventually, when we save state between restarts to `Settings` or whatever, just get the checkbox state from there as well. Seems like VSCode is also getting the value directly from `settings.json` via:
```js
toggled: ContextKeyExpr.equals('config.editor.renderControlCharacters', true)
```

**Comment by fabiospampinato** [comment]
I'm going to implement a kind of low-level library for managing flags (we are currently just recreating the entire object from scratch each time and sending it to the main process), which will be useful for shortcuts #477  too, let's wait until that's in place before updating the `checked` status of these menu items.

**Comment by afonsomatos** [comment]
Is this still ongoing? Currently, in Windows > View Menu, only "Toggle Menu Bar" is a checkbox type.

**Comment by fabiospampinato** [comment]
@afonsomatos I'm currently in the process of writing a few core libraries which we'll enable us to keep track of these things.

**Comment by fabiospampinato** [comment]
Context menus and the app menu have been rewritten, I've taken care of this 👍

**Pull request closed without merging**
