### PR TITLE
Copy-paste context menu in the editor

### LINKED ISSUE #553: Right-click in the editor does not work
- **OS Version**: Windows 10 and Linux Mint 19.1
- **Notable Version**: 1.4.0

### Current behavior

Right-click on selected text does not work in the editor

### Expected behavior

Right click opens menu with: Cut, Copy, Paste

### PR DESCRIPTION
**Pull request by prashkup**
Added a context menu to allow cut, copy and paste in the editor.

Resolves #553

### CODE REVIEW

**Comment by prashkup** [comment]
@fabiospampinato , have you checked this, if so, I would love to hear your thoughts / review, I am not too experienced ( especially with typescript ) , I might learn a thing or two!

**Comment by fabiospampinato** [comment]
@prashkup Sorry I didn't have the time to review this properly yet. Did you take a look at how vscode is implementing this? I'm thinking perhaps we could do the same, as their code should be pretty much battle-tested in this regard.

**Comment by prashkup** [comment]
Hey! 

Yes, I will take a look at how vscode is doing this.

**Comment by fabiospampinato** [comment]
This PR seems well done, thank you. I'll try to get this merged before the next release.

**Comment by fabiospampinato** [comment]
Thank you @prashkup! I've cleaned up the implemented a bit here: https://github.com/notable/notable/commit/3dabea20f3d37f7e29966033791dbb934d671258

There's still to add support for multi-cursors, and focus is lost, I think it should be preserved instead.

**Comment by prashkup** [comment]
@fabiospampinato , that's great, I will work and add support for multi-cursors and the preserving focus.

**Comment by fabiospampinato** [comment]
I added support for those a couple of commits later :+1:

**Pull request merged**
