### PR TITLE
Allow basic math?

### PR DESCRIPTION
**Pull request by moos**
This was easier than I thought! 😄  Ref: #482 . 

Edit mode:
```
The sum is ${ 2 + 2}.
The ratio is ${ Number(34/56).toPrecision(2) }
```

Display mode:
> The sum is `4`.
The ratio is `0.61`

Variables:
```
The sum is ${sum=2+2}
Number of players = ${num=6}
My portion: ${ sum/num}
```
> The sum is 4
Number of players = 5
My portion: 0.8

Beyond math:
```
My platform is ${process.platform} and cwd is ${process.cwd()}.
```
> My platform is win32 and cwd is  C:\dev\notable.

This has the same security concerns as #362, as it allows arbitrary JS execution -- but that's only a concern for note sharing from un-trusted sources.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
So you basically exposed an `eval` via the `${...}` syntax 🤔 It's cool but I try to be pretty cautious with regards to adding new syntax to the core. I think this should probably be implemented as a plugin #128 instead.

**Comment by moos** [comment]
I understand the reservation, esp. regarding security -- although I think making a note effectively "script-able" adds potential for interactivity and dynamic content.

I'd like to know what the notable community thinks - so if you don't mind keeping the PR open for a bit to see if it attracts any 👍 s.

**Comment by fabiospampinato** [comment]
> although I think making a note effectively "script-able" adds potential for interactivity and dynamic content.

That sounds interesting, I'm saying maybe this specific syntax shouldn't be implemented by the app itself but by a plugin, when that will become a thing.

> I'd like to know what the notable community thinks - so if you don't mind keeping the PR open for a bit to see if it attracts any 👍 s.

Sure 👍

**Comment by moos** [comment]
Good suggestion - done.

**Comment by mikaelmello** [comment]
I personally do not like this idea at all, but it has its pros/features. In my opinion it should only be implemented as a plugin and not as part of the base of Notable

**Comment by blakek** [comment]
I may be wrong in reading the PR, but it seems that as-is this would prevent writing template strings in notes because they'd all be executed.  For example:

    ```
    The URL format is `https://api.weather.gov/points/${latitude},${longitude}/forecast`
    ```

would show something like:

> The URL format is `[basicMath error: an error message]`

This would be a neat plugin, but I don't think it should be part of the main app.

If you do make a plugin, I would vote for attaching to language blocks or a different syntax that isn't commonly used in notes.  For example, something like this:

    System status:
    ```javascript
    %%node
    `memory free: ${os.freemem()} | total memory: ${os.totalmem()}`
    ```

...would show:

> System status:
> `memory free: 32976896 | total memory: 4294967296`

**Comment by fabiospampinato** [comment]
I'm closing this, let's keep the discussion about this on the subreddit.

**Pull request closed without merging**
